version: '3.8'

services:
  bux-mysql:
    image: mysql:8.0
    container_name: bux-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bux_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  bux-backend:
    build: ./bux-backend
    container_name: bux-backend
    depends_on:
      bux-mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bux-mysql:3306/bux_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"

  bux-frontend:
    build: ./bux-frontend
    container_name: bux-frontend
    ports:
      - "4200:80"
    depends_on:
      - bux-backend

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: jenkins-docker:with-docker
    container_name: jenkins-docker
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - type: npipe
        source: "\\\\.\\pipe\\docker_engine"
        target: "\\\\.\\pipe\\docker_engine"
    environment:
      - DOCKER_HOST=npipe:////./pipe/docker_engine

volumes:
  mysql_data:
  jenkins_home:
